# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_userevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='acme_t2d',
            name='tracking',
            field=models.CharField(choices=[(b'new_lead', b'New lead'), (b'not_reached_attempt1', b'Not reached attempt 1'), (b'not_reached_attempt2', b'Not reached attempt 2'), (b'verbally_pre-screened', b'Verbally Pre-screened'), (b'scheduled_clinic_visit', b'Scheduled Clinic Visit'), (b'screened_in_clinic', b'Screened in clinic')], default=b'new_lead', max_length=25),
        ),
    ]
