# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170531_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acme_t2d',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'no_response', b'No Response'), (b'fail_verbal_pre-screening', b'Failed Verbal Pre-Screening'), (b'fail_clinic_screening', b'Failed Clinic Screening'), (b'declined', b'Declined'), (b'enrolled', b'Enrolled')], default=b'pending', max_length=25),
        ),
    ]
